config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  authenticated :user do
    root "properties#show", as: :authenticated_root

    resources :properties do
      resources :promotions do
        get :review
        resources :conditions
      end
      resources :variables
      resources :products do
        collection do
          post :import
        end
      end
    end
  end

  namespace :api do
    namespace :v1 do
      resources :promotions, only: [:index, :show]
    end
  end

  unauthenticated :user do
    root "home#index"
  end
end

app/models/condition.rb
class Condition < ApplicationRecord

  BY = ["AND", "OR"]

  belongs_to :promotion
  has_many :groups, dependent: :destroy
  accepts_nested_attributes_for :groups, reject_if: :all_blank, allow_destroy: true

  def to_rulio(params)
    return Rulio::Condition.new(self.groups.map{|g| g.to_rulio(params)}, self.by)
  end
end

app/controllers/conditions_controller.rb
class ConditionsController < ApplicationController

    before_action :set_promotion
    before_action :set_condition, only: [:edit, :update]

    def index
        @products = {
            included: @promotion.included_products,
            excluded: @promotion.excluded_products,
        }
    end

    def new
    end

    def create
    end

    def edit

    end

    def update
        if @condition.update(condition_params)
            redirect_to property_promotion_conditions_path(@property, @promotion), notice: "Condition was successfully updated."
        else
            render :index, status: :unprocessable_entity, alert: "There were some errors updating the conditions."
        end
    end

    def destroy
    end

    private

    def set_condition
        @condition = @promotion.condition
    end

    def set_promotion
        @promotion = @property.promotions.find(params[:promotion_id])
    end

    def condition_params
        params.require(:condition).permit(:promotion, :by,
                                            groups_attributes: [:id, :_destroy, :by,
                                                                operations_attributes: [:id, :_destroy, :variable_key, :operator, :constant]])
    end

end

app/helpers/conditions_helper.rb
module ConditionsHelper
end

app/views/conditions/_condition.html.haml
%div{class: "overflow-hidden rounded-lg bg-white shadow border border-gray-400"}
    %div{class: "px-4 py-5 sm:p-6"}
        - condition.groups.each_with_index do |g, i|
            = render partial: "groups/group", locals: {g: g, i: i, c: condition}

app/views/conditions/_form.html.haml
= form_with model: condition, url: (condition.persisted? ? property_promotion_condition_path(property, promotion, condition) : property_promotion_conditions_path(property, promotion)), html: {data: {turbo: false, controller: "nested-form", nested_form_wrapper_selector_value: ".nested-form-wrapper"}, class: "rounded border border-dashed border-gray-950 p-2"} do |f|
    = render partial: "groups/template", locals: {condition: condition, f: f}
    %div{class: "grid md:grid-cols-2"}
        %div
            %h2{class: "text-base/7 font-semibold text-gray-900"} Additional Conditions
            %p{class: "mt-1 text-sm/6 text-gray-600"} Configure the additional attributes based conditions for the promotion.
        %div{class: "flex gap-2 justify-end items-center", data:{controller: "logicby"}}
            %button{data:{action: "nested-form#add"}, class: "text-sm cursor-pointer px-4 py-[calc(theme(spacing.2)-1px)] rounded-full border border-transparent bg-gray-950 shadow-sm whitespace-nowrap text-base font-medium text-white disabled:bg-gray-950 hover:bg-gray-800 disabled:opacity-40"} Add Group
            = f.select :by, Condition::BY, {}, {class: "block rounded-md border-gray-300 py-2 pl-3 pr-10 text-base focus:border-gray-900 focus:outline-none focus:ring-gray-900 sm:text-sm", data:{action: "change->logicby#updateDividers", target: ".condition-by"}}
    %div{class: "my-4"}
        = f.fields_for :groups, (condition.groups.any? ? condition.groups : condition.groups.build) do |group_fields|
            = render partial: "groups/form", locals: {f: group_fields}
        %div{data:{"nested-form-target": "target"}}
    %div{class: "mt-4 text-right"}
        = f.submit "Save Condition", class: "cursor-pointer inline-flex items-center justify-center px-4 py-[calc(theme(spacing.2)-1px)] rounded-full border border-transparent bg-gray-950 shadow-md whitespace-nowrap text-base font-medium text-white disabled:bg-gray-950 hover:bg-gray-800 disabled:opacity-40"

app/views/conditions/_products_display.html.haml
%div{class: "grid grid-cols-1 md:grid-cols-2 gap-4"}
    %div{class: "divide-y divide-gray-200 overflow-hidden rounded-lg bg-white shadow"}
        %div{class: "px-2 py-3 sm:px-6 bg-gray-950 text-white"}
            Included Products
        %div{class: "p-0 overflow-scroll h-48"}
            %ul{role: "list", class: "divide-y divide-gray-300 h-full"}
                - if products[:included].length > 0
                    = render partial: "products/product", collection: products[:included]
                - else
                    %li{class: "px-6 py-4 h-full"}
                        .relative.h-full.overflow-hidden.rounded.border.border-dashed.border-gray-950.opacity-75.flex.justify-center
                            %span.text-center.my-5 No specific products uploaded for inclusion.
                            %svg.absolute.inset-0.h-full.w-full{class: "stroke-gray-950/10", fill: "none"}
                                %defs
                                    %pattern#pattern-68d31db3-811c-4e14-a36d-77b54bde9805{height: "10", patternunits: "userSpaceOnUse", width: "10", x: "0", y: "0"}
                                        %path{d: "M-3 13 15-5M-5 5l18-18M-1 21 17 3"}
                                %rect{fill: "url(#pattern-68d31db3-811c-4e14-a36d-77b54bde9805)", height: "100%", stroke: "none", width: "100%"}
    %div{class: "divide-y divide-gray-200 overflow-hidden rounded-lg bg-white shadow"}
        %div{class: "px-2 py-3 sm:px-6 bg-gray-950 text-white"}
            Excluded Products
        %div{class: "p-0 overflow-scroll h-48"}
            %ul{role: "list", class: "divide-y divide-gray-300 h-full"}
                - if products[:excluded].length > 0
                    = render partial: "products/product", collection: products[:excluded]
                - else
                    %li{class: "px-6 py-4 h-full"}
                        .relative.h-full.overflow-hidden.rounded.border.border-dashed.border-gray-950.opacity-75.flex.justify-center
                            %span.text-center.my-5 No specific products uploaded for exclusion.
                            %svg.absolute.inset-0.h-full.w-full{class: "stroke-gray-950/10", fill: "none"}
                                %defs
                                    %pattern#pattern-68d31db3-811c-4e14-a36d-77b54bde9805{height: "10", patternunits: "userSpaceOnUse", width: "10", x: "0", y: "0"}
                                        %path{d: "M-3 13 15-5M-5 5l18-18M-1 21 17 3"}
                                %rect{fill: "url(#pattern-68d31db3-811c-4e14-a36d-77b54bde9805)", height: "100%", stroke: "none", width: "100%"}

app/views/conditions/index.html.haml
= content_for :html_class, "h-full"
= content_for :body_class, "h-full"
= content_for :main_class, "min-h-full"
%div{class: "py-6"}
    %header
        %div{class: "mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"}
            %h1{class: "text-3xl font-bold"}
                Conditions: #{@promotion.name}

%div{class: "py-2"}
    %div{class: "mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"}
        = render partial: "promotions/form_stepper", locals: {status: ["completed", "inprogress", "pending"]}
        %div{class: "mt-4 space-y-6"}
            %div{class: "space-y-6 border-b border-gray-900/10 pb-6"}
                %div{class: "grid md:grid-cols-2"}
                    %div
                        %h2{class: "text-base/7 font-semibold text-gray-900"} Product Conditions
                        %p{class: "mt-1 text-sm/6 text-gray-600"} Configure the product skus that should be included or excluded.
                    %div{class: "flex gap-2 justify-end items-center"}
                        = link_to edit_property_promotion_path(@property, @promotion), class: "cursor-pointer inline-flex items-center justify-center px-4 py-[calc(theme(spacing.2)-1px)] rounded-full border border-transparent bg-gray-950 shadow-md whitespace-nowrap text-base font-medium text-white disabled:bg-gray-950 hover:bg-gray-800 disabled:opacity-40" do
                            %svg.size-6{fill: "none", stroke: "currentColor", "stroke-width" => "1.5", viewbox: "0 0 24 24", xmlns: "http://www.w3.org/2000/svg"}
                                %path{d: "M10.5 19.5 3 12m0 0 7.5-7.5M3 12h18", "stroke-linecap" => "round", "stroke-linejoin" => "round"}
                            Edit Promotion Details
                        = link_to property_promotion_review_path(@property, @promotion), class: "cursor-pointer inline-flex items-center justify-center px-4 py-[calc(theme(spacing.2)-1px)] rounded-full border border-transparent bg-gray-950 shadow-md whitespace-nowrap text-base font-medium text-white disabled:bg-gray-950 hover:bg-gray-800 disabled:opacity-40" do
                            Review and Activate
                            %svg.size-6{fill: "none", stroke: "currentColor", "stroke-width" => "1.5", viewbox: "0 0 24 24", xmlns: "http://www.w3.org/2000/svg"}
                                %path{d: "M13.5 4.5 21 12m0 0-7.5 7.5M21 12H3", "stroke-linecap" => "round", "stroke-linejoin" => "round"}
                = render partial: "products/import", locals: {promotion: @promotion}
                = render partial: "products_display", locals: {products: @products}
            = render partial: "form", locals: {property: @property, promotion: @promotion, products: @products, condition: (@promotion.condition || Condition.new({promotion: @promotion}))}