config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  authenticated :user do
    root "properties#show", as: :authenticated_root

    resources :properties do
      resources :promotions do
        get :review
        resources :conditions
      end
      resources :variables
      resources :products do
        collection do
          post :import
        end
      end
    end
  end

  namespace :api do
    namespace :v1 do
      resources :promotions, only: [:index, :show]
    end
  end

  unauthenticated :user do
    root "home#index"
  end
end

app/models/property.rb
class Property < ApplicationRecord

    has_many :promotions, dependent: :destroy
    has_many :products, dependent: :destroy
    has_many :variables, dependent: :destroy

    validates_presence_of :name
    validates_uniqueness_of :name, :api_key, :secret

    before_create :generate_tokens

    def generate_tokens
        self.api_key = "PE-#{(SecureRandom.random_number(9e9)+1e7).to_i}"
        self.secret = (SecureRandom.random_number(9e50)+1e7).to_i
    end

    def default_variables
        self.variables.find_or_create_by!([
            {
                name: "Product SKUs",
                key: "skus",
                description: "Product SKUs are unique identifiers for the products and can be accepted as a list. Please send a \",\" separated list of SKU values to the API.",
                value_type: :list
            },
            {
                name: "Country",
                key: "country",
                description: "Country identifier helps for targeting promotions that are geographically restricted. This is a string parameter and can accept name, iso code or any other value.",
                value_type: :string
            },
            {
                name: "Language",
                key: "lang",
                description: "Language identifier helps for targeting promotions with their language variations.",
                value_type: :string
            },
            {
                name: "Page Path",
                key: "page_path",
                description: "Page path for being able to target promotions restricted and to be presented only on some pages.",
                value_type: :string
            }
        ])
    end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController

    before_action :authenticate_user!
    before_action :set_property, except: [:new, :create]

    def index
    end
    
    def show
    end

    def new
        @property = Property.new
    end

    def create
        @property = Property.new(property_params)
        if @property.save
            redirect_to property_path(@property), notice: "Property was successfully created."
        else
            render :new, status: :unprocessable_entity, alert: "There were some errors creating the property."
        end
    end

    def edit
    end

    def update
        if @property.update(property_params)
            redirect_to property_path(@property), notice: "Property was successfully updated."
        else
            render :edit, status: :unprocessable_entity
        end
    end

    def destroy
        @property.destroy
        redirect_to root_path, notice: "Property was successfully destroyed."
    end

    private

    def set_property
        if params[:id] || session[:property_id]
            @property = Property.find(params[:id] || session[:property_id])
        else
            redirect_to new_property_path
        end
    end
    
    def property_params
        params.require(:property).permit(:name)
    end
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/properties/_form.html.haml
= form_with model: property, html: {data: {turbo: false}} do |f|
    %div{class: "mt-10 grid grid-cols-1 gap-x-6 gap-y-8 sm:grid-cols-6"}
        %div{class: "sm:col-span-4"}
            = f.label :name, class: "block font-medium text-gray-900"
            %div{class: "mt-2"}
                %div{class: "flex rounded-md shadow-sm ring-1 ring-inset ring-gray-300 focus-within:ring-2 focus-within:ring-inset focus-within:ring-gray-600 sm:max-w-md"}
                    = f.text_field :name, class: "block flex-1 border-0 bg-transparent py-1.5 px-3 text-gray-900 placeholder:text-gray-400 focus:ring-0"
            - if property.errors.any? && property.errors[:name]
                %p{class: "mt-2 text-sm text-red-600", id: "name-error"}
                    = property.errors.full_messages.first
    %div{class: "mt-6 flex items-center gap-x-6"}
        = f.submit "Save Property", class: "cursor-pointer inline-flex items-center justify-center px-4 py-[calc(theme(spacing.2)-1px)] rounded-full border border-transparent bg-gray-950 shadow-md whitespace-nowrap text-base font-medium text-white disabled:bg-gray-950 hover:bg-gray-800 disabled:opacity-40"

app/views/properties/_header.html.haml
%div{class: "py-6"}
	%header
		%div{class: "mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 grid grid-cols-1 lg:grid-cols-2 gap-4"}
			%div.flex.align-middle
				%h1{class: "text-3xl font-bold"}
					= property.name
				= link_to edit_property_path(property), class: "relative rounded-full p-1 text-gray-400" do
					%svg.h-6.w-6{fill: "none", stroke: "currentColor", "stroke-width" => "1.5", viewbox: "0 0 24 24", xmlns: "http://www.w3.org/2000/svg"}
						%path{d: "m16.862 4.487 1.687-1.688a1.875 1.875 0 1 1 2.652 2.652L6.832 19.82a4.5 4.5 0 0 1-1.897 1.13l-2.685.8.8-2.685a4.5 4.5 0 0 1 1.13-1.897L16.863 4.487Zm0 0L19.5 7.125", "stroke-linecap" => "round", "stroke-linejoin" => "round"}
			%div.block
				%p.block
					%strong API Key: 
					%span #{property.api_key}
				%p.block
					%strong Secret:
					%span #{property.secret}

app/views/properties/edit.html.haml
= content_for :html_class, "h-full"
= content_for :body_class, "h-full"
= content_for :main_class, "min-h-full"
%div{class: "py-6"}
	%header
		%div{class: "mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"}
			%h1{class: "text-3xl font-bold"}
				= "Edit #{@property.name}"

%div{class: "py-2"}
	%div{class: "mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"}
		%p{class: "mt-1 text-sm/6 text-gray-600"}
			This property provides a container to bundle all your offers for a particular digital property.
			%br
			Upon creation of this property, unique API Key and Secret are generated to use for API Calls.
		= render partial: "form", locals: {property: @property}

app/views/properties/new.html.haml
= content_for :html_class, "h-full"
= content_for :body_class, "h-full"
= content_for :main_class, "min-h-full"
%div{class: "py-6"}
	%header
		%div{class: "mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"}
			%h1{class: "text-3xl font-bold"}
				New Property

%div{class: "py-2"}
	%div{class: "mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"}
		%p{class: "mt-1 text-sm/6 text-gray-600"}
			This property provides a container to bundle all your offers for a particular digital property.
			%br
			Upon creation of this property, unique API Key and Secret are generated to use for API Calls.
		= render partial: "form", locals: {property: @property}

app/views/properties/show.html.haml
= content_for :html_class, "h-full"
= content_for :body_class, "h-full"
= content_for :main_class, "min-h-full"
= render partial: "properties/header", locals: {property: @property}
%div{class: "py-2"}
	%div{class: "mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 sm:border-b sm:border-gray-200 flex items-center justify-between"}
		%div{class: "sm:hidden", data:{controller: "select-navigation"}}
			%label{class: "sr-only", for: "tabs"}
				Select a tab
			%select{id: "tabs", name: "tabs", class: "block w-full rounded-md border-gray-300 py-2 pl-3 pr-10 text-base focus:border-gray-500 focus:outline-none focus:ring-gray-500 sm:text-sm", data:{action: "change->select-navigation#navigate"}}
				%option{data:{url: property_path(@property)}, selected: (controller_name === "properties")} Promotions
				%option{data:{url: property_variables_path(@property)}, selected: (controller_name === "variables")} Variables
				%option{data:{url: property_products_path(@property)}, selected: (controller_name === "products")} Product SKUs
		%div{class: "hidden sm:block"}
			%div{class: "border-b border-gray-200"}
				%nav{class: "-mb-px flex space-x-8", "aria-label": "Tabs"}
					= link_to "Promotions", property_path(@property), class: "whitespace-nowrap border-b-2 border-fuchsia-500 px-1 py-4 text-md font-medium text-fuchsia-600"
					= link_to "Variables", property_variables_path(@property), class: "whitespace-nowrap border-b-2 border-transparent px-1 py-4 text-md font-medium text-gray-500 hover:border-gray-300 hover:text-gray-700"
					= link_to "Product SKUs", property_products_path(@property), class: "whitespace-nowrap border-b-2 border-transparent px-1 py-4 text-md font-medium text-gray-500 hover:border-gray-300 hover:text-gray-700"
		%div{class: "flex sm:ml-4 sm:mt-0"}
			= link_to "New Promotion", new_property_promotion_path(@property), class: "text-sm cursor-pointer inline-flex items-center justify-center px-4 py-[calc(theme(spacing.2)-1px)] rounded-full border border-transparent bg-gray-950 shadow-md whitespace-nowrap text-base font-medium text-white disabled:bg-gray-950 hover:bg-gray-800 disabled:opacity-40"
%div{class: "py-2"}
	%div{class: "mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"}
		%ul{role: "list", class: "divide-y divide-gray-100"}
			= render @property.promotions