config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  authenticated :user do
    root "properties#show", as: :authenticated_root

    resources :properties do
      resources :promotions do
        get :review
        resources :conditions
      end
      resources :variables
      resources :products do
        collection do
          post :import
        end
      end
    end
  end

  namespace :api do
    namespace :v1 do
      resources :promotions, only: [:index, :show]
    end
  end

  unauthenticated :user do
    root "home#index"
  end
end

app/views/shared/_authenticated_nav.html.haml
%nav.border-b.border-gray-200.bg-white{data:{controller: "mobile-menu"}}
  .mx-auto.max-w-7xl.px-4.sm:px-6.lg:px-8
    .flex.h-16.justify-between
      .flex
        .flex.flex-shrink-0.items-center
          = render partial: "shared/logo"
        .hidden.sm:-my-px.sm:ml-6.sm:flex.sm:space-x-8
          - if @property.persisted?
            = link_to "Promotions", property_path(@property), class: "inline-flex items-center border-b-2 px-1 pt-1 text-sm font-medium #{ (controller_name == "properties" && action_name == "show") ? "border-fuchsia-500 text-fuchsia-600" : "border-transparent text-gray-500 hover:border-gray-300 hover:text-gray-700"}"
            = link_to "Variables", property_variables_path(@property), class: "inline-flex items-center border-b-2 px-1 pt-1 text-sm font-medium #{ (controller_name == "variables" && action_name == "index") ? "border-fuchsia-500 text-fuchsia-600" : "border-transparent text-gray-500 hover:border-gray-300 hover:text-gray-700"}"
            = link_to "Products", property_products_path(@property), class: "inline-flex items-center border-b-2 px-1 pt-1 text-sm font-medium #{ (controller_name == "products" && action_name == "index") ? "border-fuchsia-500 text-fuchsia-600" : "border-transparent text-gray-500 hover:border-gray-300 hover:text-gray-700"}"
      %div.flex
        .flex.ml-6.items-center
          - if @property.persisted?
            .relative.flex{data: {controller: "dropdown"}}
              %div{class: "relative flex relative group/item"}
                %svg{"aria-hidden" => "true", class: "hidden absolute -top-2 -left-2 group-first/item:block size-[15px] fill-black/10", viewbox: "0 0 15 15"}
                  %path{d: "M8 0H7V7H0V8H7V15H8V8H15V7H8V0Z"}
                %svg{"aria-hidden" => "true", class: "absolute -top-2 -right-2 size-[15px] fill-black/10", viewbox: "0 0 15 15"}
                  %path{d: "M8 0H7V7H0V8H7V15H8V8H15V7H8V0Z"}
                %svg{"aria-hidden" => "true", class: "hidden absolute -bottom-2 -left-2 group-last/row:group-first/item:block size-[15px] fill-black/10", viewbox: "0 0 15 15"}
                  %path{d: "M8 0H7V7H0V8H7V15H8V8H15V7H8V0Z"}
                %svg{"aria-hidden" => "true", class: "hidden absolute -bottom-2 -right-2 group-last/row:block size-[15px] fill-black/10", viewbox: "0 0 15 15"}
                  %path{d: "M8 0H7V7H0V8H7V15H8V8H15V7H8V0Z"}
                %button{class: "flex items-center px-4 py-3 text-base font-medium text-gray-950 bg-blend-multiply hover:bg-black/[2.5%]", role: :button, data:{action: "dropdown#toggle click@window->dropdown#hide"}}
                  #{@property.name}
              %div{"aria-labelledby" => "user-menu-button", "aria-orientation" => "vertical", role: "menu", tabindex: "-1", 
                  data:{
                    "dropdown-target": "menu",
                    "transition-enter-active": "transition ease-out duration-200",
                    "transition-enter-from": "transform opacity-0 scale-95",
                    "transition-enter-to": "transform opacity-100 scale-100",
                    "transition-leave-active": "transition ease-in duration-75",
                    "transition-leave-from": "transform opacity-100 scale-100",
                    "transition-leave-to": "transform opacity-0 scale-95",
                  }, 
                  class: "absolute right-0 z-10 mt-12 w-48 origin-top-right rounded-md bg-white py-1 shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none"}
                - properties = Property.where.not(id: @property.id)
                - if properties
                  - properties.each do |p|
                    = link_to p.name, property_path(p), role: :menuitem, tabindex: -1, class: "block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100"
                .relative
                  .absolute.inset-0.flex.items-center
                    .w-full.border-t.border-gray-300
                = link_to "New Property", new_property_path, role: :menuitem, tabindex: -1, class: "block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100"
          .hidden.sm:block.relative.ml-3{data: {controller: "dropdown"}}
            %div
              %button#user-menu-button.relative.flex.max-w-xs.items-center.rounded-full.bg-white.text-sm.focus:outline-none.focus:ring-2.focus:ring-indigo-500.focus:ring-offset-2{"aria-expanded" => "false", "aria-haspopup" => "true", type: "button", data:{action: "dropdown#toggle click@window->dropdown#hide"}}
                %span.absolute{class: "-inset-1.5"}
                %span.sr-only Open user menu
                %div{class: "h-8 w-8 rounded-full flex items-center justify-center bg-gray-950 text-white"} #{current_user.name.initials}
            %div{"aria-labelledby" => "user-menu-button", "aria-orientation" => "vertical", role: "menu", tabindex: "-1", 
                data:{
                  "dropdown-target": "menu",
                  "transition-enter-active": "transition ease-out duration-200",
                  "transition-enter-from": "transform opacity-0 scale-95",
                  "transition-enter-to": "transform opacity-100 scale-100",
                  "transition-leave-active": "transition ease-in duration-75",
                  "transition-leave-from": "transform opacity-100 scale-100",
                  "transition-leave-to": "transform opacity-0 scale-95",
                }, 
                class: "absolute right-0 z-10 mt-2 w-48 origin-top-right rounded-md bg-white py-1 shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none"}
              = link_to "Your Profile", edit_user_registration_path, id: "user-profile-link", role: :menuitem, tabindex: -1, class: "block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100"
              = link_to "Logout", destroy_user_session_path, data: {turbo_method: :delete}, id: "user-signout-link", role: :menuitem, tabindex: -1, class: "block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100"
        .-mr-2.flex.items-center.sm:hidden
          / Mobile menu button
          %button.relative.inline-flex.items-center.justify-center.rounded-md.p-2.text-gray-950.hover:bg-gray-950.hover:text-white.focus:outline-none.focus:ring-2.focus:ring-indigo-500.focus:ring-offset-2{"aria-controls" => "mobile-menu", "aria-expanded" => "false", type: "button", data: {action: "click->mobile-menu#toggle"}}
            %span.absolute{class: "-inset-0.5"}
            %span.sr-only Open main menu
            / Menu open: "hidden", Menu closed: "block"
            %svg.block.h-6.w-6{"aria-hidden" => "true", "data-slot" => "icon", fill: "none", stroke: "currentColor", "stroke-width" => "1.5", viewbox: "0 0 24 24", "data-mobile-menu-target": "icon"}
              %path{d: "M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5", "stroke-linecap" => "round", "stroke-linejoin" => "round"}
            / Menu open: "block", Menu closed: "hidden"
            %svg.hidden.h-6.w-6{"aria-hidden" => "true", "data-slot" => "icon", fill: "none", stroke: "currentColor", "stroke-width" => "1.5", viewbox: "0 0 24 24", "data-mobile-menu-target": "icon"}
              %path{d: "M6 18 18 6M6 6l12 12", "stroke-linecap" => "round", "stroke-linejoin" => "round"}
  / Mobile menu, show/hide based on menu state.
  #mobile-menu.hidden.sm:hidden{"data-mobile-menu-target": "menu"}
    .space-y-1.pb-3.pt-2
      - if @property.persisted?
        = link_to "Promotions", property_path(@property), class: "block border-l-4 py-2 pl-3 pr-4 text-base font-medium #{ (controller_name == "properties" && action_name == "show") ? "border-indigo-500 bg-indigo-50 text-indigo-700" : "text-gray-600 hover:border-gray-300 hover:bg-gray-50 hover:text-gray-800"}"
        = link_to "Variables", property_variables_path(@property), class: "block border-l-4 py-2 pl-3 pr-4 text-base font-medium #{ (controller_name == "variables" && action_name == "index") ? "border-indigo-500 bg-indigo-50 text-indigo-700" : "text-gray-600 hover:border-gray-300 hover:bg-gray-50 hover:text-gray-800"}"
        = link_to "Products", property_products_path(@property), class: "block border-l-4 py-2 pl-3 pr-4 text-base font-medium #{ (controller_name == "products" && action_name == "index") ? "border-indigo-500 bg-indigo-50 text-indigo-700" : "text-gray-600 hover:border-gray-300 hover:bg-gray-50 hover:text-gray-800"}"
    .border-t.border-gray-200.pb-3.pt-4
      .px-4
        .text-base.block.font-medium.text-gray-800 #{current_user.name}
        .text-sm.block.font-medium.text-gray-500 #{current_user.email}
      .mt-3.space-y-1
        = link_to "Your Profile", edit_user_registration_path, id: "user-profile-link", role: :menuitem, tabindex: -1, class: "block px-4 py-2 text-base font-medium text-gray-500 hover:bg-gray-100 hover:text-gray-800"
        = link_to "Logout", destroy_user_session_path, data: {turbo_method: :delete}, id: "user-signout-link", role: :menuitem, tabindex: -1, class: "block px-4 py-2 text-base font-medium text-gray-500 hover:bg-gray-100 hover:text-gray-800"

app/views/shared/_banner.html.haml
%div{class: "bg-gray-900 px-6 py-2.5 sm:px-3.5"}
    %div{class: "flex items-center mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"}
        %p{class: "text-sm/6 text-white"}
            %strong{class: "font-semibold"}
                = (alert ? "Alert" : "Notice")
            %svg.mx-2.inline.fill-current{"aria-hidden" => "true", class: "h-0.5 w-0.5", viewbox: "0 0 2 2"}
                %circle{cx: "1", cy: "1", r: "1"}
            = alert || notice
        .flex.flex-1.justify-end
            %button{class: "-m-3 p-3 focus-visible:outline-offset-[-4px]", type: "button"}
                %span.sr-only Dismiss
                %svg.h-5.w-5.text-white{"aria-hidden" => "true", "data-slot" => "icon", fill: "currentColor", viewbox: "0 0 20 20"}
                    %path{d: "M6.28 5.22a.75.75 0 0 0-1.06 1.06L8.94 10l-3.72 3.72a.75.75 0 1 0 1.06 1.06L10 11.06l3.72 3.72a.75.75 0 1 0 1.06-1.06L11.06 10l3.72-3.72a.75.75 0 0 0-1.06-1.06L10 8.94 6.28 5.22Z"}

app/views/shared/_logo.html.haml
%svg.h-9.overflow-visible{height: "34", viewbox: "0 0 34 34", width: "34"}
    %g{opacity: "1", style: "transform: none; transform-origin: 17.0005px 17.0005px 0px;"}
        %path{d: "M19.5986 18.5005C18.7702 19.9354 16.9354 20.427 15.5005 19.5986C14.0656 18.7701 13.574 16.9354 14.4024 15.5005C15.2309 14.0656 17.0656 13.574 18.5005 14.4024C19.9354 15.2308 20.427 17.0656 19.5986 18.5005Z"}
    %g{opacity: "1", style: "transform: none; transform-origin: 17px 17.0004px 0px;"}
        %path{d: "M23.2324 10.2074C22.6801 11.1639 21.4569 11.4917 20.5003 10.9394C19.5437 10.3871 19.216 9.16395 19.7683 8.20736C20.3205 7.25078 21.5437 6.92303 22.5003 7.47531C23.4569 8.0276 23.7846 9.25078 23.2324 10.2074Z"}
        %path{d: "M19.7683 25.7933C19.216 24.8367 19.5437 23.6135 20.5003 23.0612C21.4569 22.5089 22.6801 22.8367 23.2324 23.7933C23.7847 24.7498 23.4569 25.973 22.5003 26.5253C21.5437 27.0776 20.3206 26.7498 19.7683 25.7933Z"}
        %path{d: "M26 19C24.8954 19 24 18.1046 24 17C24 15.8955 24.8954 15 26 15C27.1046 15 28 15.8955 28 17C28 18.1046 27.1046 19 26 19Z"}
        %path{d: "M14.2324 25.7933C13.6801 26.7499 12.4569 27.0777 11.5003 26.5254C10.5437 25.9731 10.216 24.7499 10.7683 23.7933C11.3205 22.8367 12.5437 22.509 13.5003 23.0613C14.4569 23.6136 14.7846 24.8367 14.2324 25.7933Z"}
        %path{d: "M10.7682 10.2073C10.216 9.25078 10.5437 8.0276 11.5003 7.47532C12.4569 6.92303 13.6801 7.25078 14.2323 8.20737C14.7846 9.16395 14.4569 10.3871 13.5003 10.9394C12.5437 11.4917 11.3205 11.1639 10.7682 10.2073Z"}
        %path{d: "M8 19C6.89543 19 6 18.1045 6 17C6 15.8954 6.89543 15 8 15C9.10457 15 10 15.8954 10 17C10 18.1045 9.10457 19 8 19Z"}
    %g{opacity: "1", style: "transform: none; transform-origin: 17px 17px 0px;"}
        %path{d: "M25.8662 3.6447C25.5901 4.12299 24.9785 4.28686 24.5002 4.01072C24.0219 3.73458 23.858 3.12299 24.1342 2.6447C24.4103 2.1664 25.0219 2.00253 25.5002 2.27867C25.9785 2.55481 26.1424 3.1664 25.8662 3.6447Z"}
        %path{d: "M33 18C32.4477 18 32 17.5522 32 17C32 16.4477 32.4477 16 33 16C33.5522 16 34 16.4477 34 17C34 17.5522 33.5522 18 33 18Z"}
        %path{d: "M31.3556 9.86619C30.8773 10.1424 30.2658 9.97846 29.9896 9.50017C29.7135 9.02187 29.8773 8.41028 30.3556 8.13414C30.8339 7.858 31.4455 8.02187 31.7217 8.50017C31.9978 8.97846 31.8339 9.59005 31.3556 9.86619Z"}
        %path{d: "M30.3556 25.8662C29.8773 25.5901 29.7134 24.9785 29.9896 24.5002C30.2657 24.0219 30.8773 23.858 31.3556 24.1342C31.8339 24.4103 31.9978 25.0219 31.7216 25.5002C31.4455 25.9785 30.8339 26.1424 30.3556 25.8662Z"}
        %path{d: "M16 33C16 32.4477 16.4477 32 17 32C17.5523 32 18 32.4477 18 33C18 33.5523 17.5523 34 17 34C16.4477 34 16 33.5523 16 33Z"}
        %path{d: "M24.1341 31.3557C23.858 30.8774 24.0219 30.2658 24.5002 29.9896C24.9785 29.7135 25.5901 29.8774 25.8662 30.3557C26.1423 30.834 25.9785 31.4455 25.5002 31.7217C25.0219 31.9978 24.4103 31.834 24.1341 31.3557Z"}
        %path{d: "M9.8662 31.3556C9.59005 31.8339 8.97846 31.9978 8.50017 31.7216C8.02188 31.4455 7.858 30.8339 8.13415 30.3556C8.41029 29.8773 9.02188 29.7134 9.50017 29.9896C9.97846 30.2657 10.1424 30.8773 9.8662 31.3556Z"}
        %path{d: "M1 18C0.447715 18 -3.44684e-08 17.5523 0 17C3.44684e-08 16.4477 0.447715 16 1 16C1.55228 16 2 16.4477 2 17C2 17.5523 1.55228 18 1 18Z"}
        %path{d: "M3.6447 25.8662C3.1664 26.1424 2.55481 25.9785 2.27867 25.5002C2.00253 25.0219 2.1664 24.4103 2.6447 24.1342C3.12299 23.858 3.73458 24.0219 4.01072 24.5002C4.28686 24.9785 4.12299 25.5901 3.6447 25.8662Z"}
        %path{d: "M2.6447 9.8662C2.1664 9.59005 2.00253 8.97846 2.27867 8.50017C2.55481 8.02188 3.1664 7.858 3.6447 8.13415C4.12299 8.41029 4.28686 9.02188 4.01072 9.50017C3.73458 9.97846 3.12299 10.1424 2.6447 9.8662Z"}
        %path{d: "M16 1C16 0.447715 16.4477 -4.87226e-08 17 0C17.5523 4.87226e-08 18 0.447715 18 1C18 1.55228 17.5523 2 17 2C16.4477 2 16 1.55228 16 1Z"}
        %path{d: "M8.13415 3.6447C7.858 3.16641 8.02188 2.55482 8.50017 2.27867C8.97846 2.00253 9.59005 2.16641 9.8662 2.6447C10.1424 3.12299 9.97846 3.73458 9.50017 4.01072C9.02188 4.28687 8.41029 4.12299 8.13415 3.6447Z"}