config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  authenticated :user do
    root "properties#show", as: :authenticated_root

    resources :properties do
      resources :promotions do
        get :review
        resources :conditions
      end
      resources :variables
      resources :products do
        collection do
          post :import
        end
      end
    end
  end

  namespace :api do
    namespace :v1 do
      resources :promotions, only: [:index, :show]
    end
  end

  unauthenticated :user do
    root "home#index"
  end
end

app/models/variable.rb
class Variable < ApplicationRecord

  enum :value_type, [:string, :list, :decimal, :boolean]

  validates_presence_of :name, :description, :key, :value_type

  belongs_to :property
end

app/controllers/variables_controller.rb
class VariablesController < ApplicationController

    before_action :authenticate_user!
    before_action :set_variable, except: [:index, :new, :create]

    def index
        @variables = @property.variables
    end

    def show
    end

    def new
        @variable = @property.variables.new
    end

    def create
        @variable = @property.variables.new(variable_params)
        if @variable.save
            redirect_to property_variables_path(@property), notice: "Variable was successfully created."
        else
            render :new, status: :unprocessable_entity, alert: "There were some errors creating the variable."
        end
    end

    def edit
    end

    def update
        if @variable.update(variable_params)
            redirect_to property_variables_path(@property), notice: "Variable was successfully updated."
        else
            render :edit, status: :unprocessable_entity, alert: "There were some errors updating the variable."
        end
    end

    def destroy
        @variable.destroy
        redirect_to property_variables_path(@property), notice: "Variable was successfully destroyed."
    end

    private

    def set_variable
        @variable = @property.variables.find(params[:id])
    end

    def variable_params
        params.require(:variable).permit(:property, :name, :description, :key, :value_type, :possible_values)
    end

end

app/helpers/variables_helper.rb
module VariablesHelper
end

app/views/variables/_form.html.haml
= form_with model: variable, url: (variable.persisted? ? property_variable_path(property, variable) : property_variables_path(property)), html: {data: {turbo: false}} do |f|
    %div{class: "mt-10 grid grid-cols-1 gap-x-6 gap-y-8 sm:grid-cols-6"}
        %div{class: "sm:col-span-3"}
            = f.label :name, class: "block text-sm/6 font-medium text-gray-900"
            %small.text-gray-600
                Name for the variable is simply for the purposes of user-friendly conditional building.
            %div.mt-2
                = f.text_field :name, class: "block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-gray-600 sm:text-sm/6"            
            - if variable.errors.any? && variable.errors[:name]
                %p{class: "mt-2 text-sm text-red-600", id: "name-error"}
                    Name cannot be blank.
        %div{class: "sm:col-span-3"}
            = f.label :key, class: "block text-sm/6 font-medium text-gray-900"
            %small.text-gray-600
                This is the key that is required to be passed in the URL to send the value to the API.
            %div.mt-2
                = f.text_field :key, class: "block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-gray-600 sm:text-sm/6"            
            - if variable.errors.any? && variable.errors[:key]
                %p{class: "mt-2 text-sm text-red-600", id: "name-error"}
                    Key cannot be blank.
        %div{class: "sm:col-span-6"}
            = f.label :description, class: "block text-sm/6 font-medium text-gray-900"
            %small.text-gray-600
                Description helps explain the purpose of the variable. Include any details that might be useful while building conditions.
            %div.mt-2
                = f.text_area :description, class: "block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-gray-600 sm:text-sm/6", rows: 3
            - if variable.errors.any? && variable.errors[:description]
                %p{class: "mt-2 text-sm text-red-600", id: "name-error"}
                    Description cannot be blank.
        %div{class: "sm:col-span-3"}
            = f.label :value_type, class: "block text-sm/6 font-medium text-gray-900"
            %small.text-gray-600
                Please set the value type to one of the following.
            %div.mt-2
                = f.select :value_type, Variable.value_types.map{|vt, v| [vt.capitalize, vt.to_sym]}, {include_blank: false}, {class: "mt-2 block w-full rounded-md border-0 py-1.5 pl-3 pr-10 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 focus:ring-2 focus:ring-gray-600 sm:text-sm/6"}
            - if variable.errors.any? && variable.errors[:value_type]
                %p{class: "mt-2 text-sm text-red-600", id: "name-error"}
                    Value Type cannot be blank.
        %div{class: "sm:col-span-3"}
            = f.label :possible_values, class: "block text-sm/6 font-medium text-gray-900"
            %small.text-gray-600
                Provide a comma-separated list of values here to restrict the variable to a specific set of options.
            %div.mt-2
                = f.text_field :possible_values, class: "block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-gray-600 sm:text-sm/6"            
    %div{class: "mt-6 flex items-center gap-x-6"}
        = f.submit "Save variable", class: "cursor-pointer inline-flex items-center justify-center px-4 py-[calc(theme(spacing.2)-1px)] rounded-full border border-transparent bg-gray-950 shadow-md whitespace-nowrap text-base font-medium text-white disabled:bg-gray-950 hover:bg-gray-800 disabled:opacity-40"
        = link_to "Cancel", property_variables_path(property), class: "cursor-pointer inline-flex items-center justify-center px-4 py-[calc(theme(spacing.2)-1px)] rounded-full border border-gray-950 bg-transparent shadow-md whitespace-nowrap text-base font-medium hover:text-white disabled:bg-gray-950 hover:bg-gray-800 disabled:opacity-40"

app/views/variables/_variable.html.haml
%li{class: "relative flex flex-wrap items-center justify-between gap-x-6 gap-y-4 py-5 sm:flex-nowrap"}
    %div
        %p{class: "text-md/6 font-semibold text-gray-900"}
            #{variable.name}
        %div{class: "mt-1 flex items-center gap-x-2 text-sm text-gray-500"}
            #{variable.description}
    %div{class: "flex items-center justify-between gap-x-4"}
        %div{class: "mt-1 flex items-center gap-x-1.5"}
            - variable_class = ""
            - case variable.value_type
            - when "string"
                - variable_class = "bg-blue-50 text-blue-700 ring-blue-700/10"
            - when "list"
                - variable_class = "bg-indigo-50 text-indigo-700 ring-indigo-700/10"
            - when "decimal"
                - variable_class = "bg-green-50 text-green-700 ring-green-600/20"
            - when "integer"
                - variable_class = "bg-pink-50 text-pink-700 ring-pink-700/10"
            - when "boolean"
                - variable_class = "bg-yellow-50 text-yellow-800 ring-yellow-600/20"
            %span{class: "inline-flex items-center rounded-md px-2 py-1 text-xs font-medium ring-1 ring-inset #{variable_class}"} #{variable.value_type.capitalize}
        %div{class: "mt-1 flex items-center gap-x-1.5"}
            = link_to edit_property_variable_path(property, variable), class: "cursor-pointer p-1.5" do
                %svg.h-5.w-5{fill: "none", stroke: "currentColor", "stroke-width" => "1.5", viewbox: "0 0 24 24", xmlns: "http://www.w3.org/2000/svg"}
                    %path{d: "m16.862 4.487 1.687-1.688a1.875 1.875 0 1 1 2.652 2.652L6.832 19.82a4.5 4.5 0 0 1-1.897 1.13l-2.685.8.8-2.685a4.5 4.5 0 0 1 1.13-1.897L16.863 4.487Zm0 0L19.5 7.125", "stroke-linecap" => "round", "stroke-linejoin" => "round"}

app/views/variables/edit.html.haml
= content_for :html_class, "h-full"
= content_for :body_class, "h-full"
= content_for :main_class, "min-h-full"
%div{class: "py-6"}
	%header
		%div{class: "mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"}
			%h1{class: "text-3xl font-bold"}
				Edit: #{@variable.name}

%div{class: "py-2"}
	%div{class: "mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"}
		%p{class: "mt-1 text-sm/6 text-gray-600"}
			Variables are acceptable parameters for a Property by the API to further conditionally deliver the promotions.
			%br
			Please read the instructions provided for further context of the configuration.
		= render partial: "form", locals: {property: @property, variable: @variable}

app/views/variables/index.html.haml
= content_for :html_class, "h-full"
= content_for :body_class, "h-full"
= content_for :main_class, "min-h-full"
= render partial: "properties/header", locals: {property: @property}
%div{class: "py-2"}
	%div{class: "mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 sm:border-b sm:border-gray-200 flex items-center justify-between"}
		%div{class: "sm:hidden", data:{controller: "select-navigation"}}
			%label{class: "sr-only", for: "tabs"}
				Select a tab
			%select{id: "tabs", name: "tabs", class: "block w-full rounded-md border-gray-300 py-2 pl-3 pr-10 text-base focus:border-gray-500 focus:outline-none focus:ring-gray-500 sm:text-sm", data:{action: "change->select-navigation#navigate"}}
				%option{data:{url: property_path(@property)}, selected: (controller_name === "properties")} Promotions
				%option{data:{url: property_variables_path(@property)}, selected: (controller_name === "variables")} Variables
				%option{data:{url: property_products_path(@property)}, selected: (controller_name === "products")} Product SKUs
		%div{class: "hidden sm:block"}
			%div{class: "border-b border-gray-200"}
				%nav{class: "-mb-px flex space-x-8", "aria-label": "Tabs"}
					= link_to "Promotions", property_path(@property), class: "whitespace-nowrap border-b-2 border-transparent px-1 py-4 text-md font-medium text-gray-500 hover:border-gray-300 hover:text-gray-700"
					= link_to "Variables", property_variables_path(@property), class: "whitespace-nowrap border-b-2 border-fuchsia-500 px-1 py-4 text-md font-medium text-fuchsia-600"
					= link_to "Product SKUs", property_products_path(@property), class: "whitespace-nowrap border-b-2 border-transparent px-1 py-4 text-md font-medium text-gray-500 hover:border-gray-300 hover:text-gray-700"
		%div{class: "flex sm:ml-4 sm:mt-0"}
			= link_to "New Attribute", new_property_variable_path(@property), class: "text-sm cursor-pointer inline-flex items-center justify-center px-4 py-[calc(theme(spacing.2)-1px)] rounded-full border border-transparent bg-gray-950 shadow-md whitespace-nowrap text-base font-medium text-white disabled:bg-gray-950 hover:bg-gray-800 disabled:opacity-40"
%div{class: "py-2"}
	%div{class: "mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"}
		%div{class: "overflow-hidden"}
			%ul{role: "list", class: "divide-y divide-gray-100"}
				- if @variables.any?
					= render partial: "variables/variable", collection: @variables, locals: {property: @property}
				- else
					%li{class: "px-6 py-4 h-full"}
						.relative.h-16.overflow-hidden.rounded.border.border-dashed.border-gray-400.opacity-75.flex.justify-center.items-center.h-full
							%span.text-center.my-5 Property variables will presented here. Property variables are acceptable key value pairs acceptable for promotion conditions.
							%svg.absolute.inset-0.h-full.w-full{class: "stroke-gray-900/10", fill: "none"}
								%defs
									%pattern#pattern-68d31db3-811c-4e14-a36d-77b54bde9805{height: "10", patternunits: "userSpaceOnUse", width: "10", x: "0", y: "0"}
										%path{d: "M-3 13 15-5M-5 5l18-18M-1 21 17 3"}
								%rect{fill: "url(#pattern-68d31db3-811c-4e14-a36d-77b54bde9805)", height: "100%", stroke: "none", width: "100%"}

app/views/variables/new.html.haml
= content_for :html_class, "h-full"
= content_for :body_class, "h-full"
= content_for :main_class, "min-h-full"
%div{class: "py-6"}
	%header
		%div{class: "mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"}
			%h1{class: "text-3xl font-bold"}
				New Variable

%div{class: "py-2"}
	%div{class: "mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"}
		%p{class: "mt-1 text-sm/6 text-gray-600"}
			Variables are acceptable parameters for a Property by the API to further conditionally deliver the promotions.
			%br
			Please read the instructions provided for further context of the configuration.
		= render partial: "form", locals: {property: @property, variable: @variable}